stages:
  - sync

sync_repo:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    - git clone --mirror "$GITHUB_REPO_URL" repo-mirror
    - cd repo-mirror
    - git remote set-url --push origin "https://oauth2:${GITLAB_PAT}@gitlab.com/${CI_PROJECT_PATH}.git"
    - git push --mirror
