version: '1'

name: particle-life

services:
  caddy:
    image: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy-config:/config
      - caddy-data:/data

volumes:
  caddy-config:
  caddy-data: